collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 1
color:
  saturation: 0
  brandStrength: 1
  lightness: 0.9531915
  brandColors:
    - '#AD9C8B'
    - '#FFF0CF'
    - '#D14A2C'
    - '#663F2E'
    - '#7D1306'
  rhythmicContrast: 0.08297873
layout_spectrum: 1
name: Agenttest
