layout_spectrum: 1
typography_spectrum: 1
color:
  saturation: 0
  lightness: 1
  brandStrength: 1
  brandColors:
    - '#AD9C8B'
    - '#FFF0CF'
    - '#D14A2C'
    - '#663F2E'
    - '#7D1306'
  rhythmicContrast: 1
name: Agenttest
